# Generated by Django 6.0.5 on 2026-05-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Celulares', '0003_add_email_to_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
