# Generated by Django 4.2.30 on 2026-05-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda_Celulares', '0005_add_lista_deseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
